### PR TITLE
Titulo: 3rd line is added in .txt into rama-JD

### PR DESCRIPTION
**Pull request by joseluisdiaz9**
DescriptionPull Request:  3rd line is added in .txt into rama-JD

### CODE REVIEW

**Comment by joseluisdiaz9** [comment]
Hi, I have sent you a new change on  z.txt in to Rama, pls verify it

**Review by josediazvarela — COMMENTED** [review]
Oye ponle un punto n la 3r linea

**Comment by josediazvarela** [comment]
ok ya le reviso

**Comment by josediazvarela** [comment]
Oye he revisado y no hay ningun commit o cambio... sera q no lo subiste!!!

**Comment by joseluisdiaz9** [comment]
Si tenias razon.. acabo de subir, pls check it

**Review by josediazvarela — APPROVED** [review]
It is approved!!! @ @... Haz el merge!!

**Pull request merged**
